# Generated by Django 4.0.6 on 2022-09-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0002_remove_person_aadhar_remove_person_pancard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='checkbook',
            field=models.BooleanField(default=False, verbose_name='Check Book'),
        ),
    ]
